# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

# Below is an example of intersphinx mapping declaration
# Add more mappings depending on what manual you want to link to
# Remove entirely if you don't need cross-linking

---
conf.py:
  copyright: 2018
  project: video_shariff
  version: 1.0.0
  release: 1.0.0
  latex_documents:
  - Index
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual
    github_branch: latest
...
